### ISSUE TITLE
2019 Oxygen

### ISSUE THREAD

**Issue by Br-Johnson** [HakaiInstitute/iys-oos#8]
Description: NONE
Source Language: Russian
Status: Processed & available as a spreadsheet
Group: TINRO
Data Access: NONE

**Comment by jclgan** [comment]
Need more information about how different oxygen measurements were collected

**Comment by timvdstap** [comment]
@jclgan Am I correct in assuming that the feature/oxygen branch is 'complete', and can be merged with the develop branch perhaps? Is it perhaps a good idea to have Anna Vazhova look at the reformatted dataset and the controlled vocabulary chosen to describe the variables?

**Comment by jclgan** [comment]
Yes I'd say it's complete, since it was worked on adjacent to the nutrients dataset. Wouldn't hurt to run our controlled vocab for each dataset against the data provider. Maybe a simple table - LHS is the original column heading, and RHS is the controlled vocab term, for example:

| Variable              | Description                                                                                                                                                                         |
|-----------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| O2 [ml/l]             | Concentration of oxygen {O2 CAS 7782-44-7} per unit volume of the water body [dissolved plus reactive particulate phase] by Winkler titration                                       |
| [%] oxygen saturation | Saturation of oxygen {O2 CAS 7782-44-7} in the water body [dissolved plus reactive particulate phase] by Winkler titration and computation from concentration using Weiss algorithm |

**Comment by timvdstap** [comment]
> Yes I'd say it's complete, since it was worked on adjacent to the nutrients dataset. Wouldn't hurt to run our controlled vocab for each dataset against the data provider. Maybe a simple table - LHS is the original column heading, and RHS is the controlled vocab term description, for example:
> 
> Variable	Description
> O2 [ml/l]	Concentration of oxygen {O2 CAS 7782-44-7} per unit volume of the water body [dissolved plus reactive particulate phase] by Winkler titration
> [%] oxygen saturation	Saturation of oxygen {O2 CAS 7782-44-7} in the water body [dissolved plus reactive particulate phase] by Winkler titration and computation from concentration using Weiss algorithm

Yeah I like that, I think that would be a good thing to do with all scientists/data providers, to loop them (back) into the standardization process.
